### ISSUE TITLE
It worked for a moment, but it ended thrwing an error

### ISSUE THREAD

**Issue by sergiohzph** [e43b/Kemono-and-Coomer-Downloader#7]
Hi, I was downloading a profile from Coomer, it downloaded some posts but after a while it gave me this error:
```
Traceback (most recent call last):
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(92274688 bytes read, 485035764 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 977, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 872, in _raw_read
    with self._error_catcher():
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(92274688 bytes read, 485035764 more expected)', IncompleteRead(92274688 bytes read, 485035764 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Kemono-and-Coomer-Downloader\codeen\code\profile.py", line 216, in <module>
    baixar_conteudo(post['link'], config)
  File "D:\Software\Kemono-and-Coomer-Downloader\codeen\code\profile.py", line 139, in baixar_conteudo
    attachment_response = requests.get(attachment_url)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 746, in send
    r.content
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(92274688 bytes read, 485035764 more expected)', IncompleteRead(92274688 bytes read, 485035764 more expected))
```
Do I need an specific version of Python to make this to work without problems?

**Comment by e43b** [comment]
> Hi, I was downloading a profile from Coomer, it downloaded some posts but after a while it gave me this error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher
>     yield
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 894, in _raw_read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
> urllib3.exceptions.IncompleteRead: IncompleteRead(92274688 bytes read, 485035764 more expected)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 820, in generate
>     yield from self.raw.stream(chunk_size, decode_content=True)
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 1060, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 977, in read
>     data = self._raw_read(amt)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 872, in _raw_read
>     with self._error_catcher():
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
>     self.gen.throw(value)
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\response.py", line 772, in _error_catcher
>     raise ProtocolError(arg, e) from e
> urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(92274688 bytes read, 485035764 more expected)', IncompleteRead(92274688 bytes read, 485035764 more expected))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Software\Kemono-and-Coomer-Downloader\codeen\code\profile.py", line 216, in <module>
>     baixar_conteudo(post['link'], config)
>   File "D:\Software\Kemono-and-Coomer-Downloader\codeen\code\profile.py", line 139, in baixar_conteudo
>     attachment_response = requests.get(attachment_url)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 746, in send
>     r.content
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 902, in content
>     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 822, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(92274688 bytes read, 485035764 more expected)', IncompleteRead(92274688 bytes read, 485035764 more expected))
> ```
> 
> Do I need an specific version of Python to make this to work without problems?

Hello, thank you very much for the report. The error is not related to the project itself, but rather to a connection failure during the download of a large file. This happened because something interrupted the download before it was completed, and this can occur for various reasons. I would like to run a test before modifying the project. Could you please send the profile link and the specific post where the error occurred? I look forward to hearing from you

**Comment by e43b** [comment]
> https://coomer.su/onlyfans/user/notsoamateurofficial/



> > Could you please send the profile link and the specific post where the error occurred? I look forward to hearing from you
> 
> https://coomer.su/onlyfans/user/notsoamateurofficial/ I'm not sure about what post failed, sorry. But it didn't download much, after the 4th or 5th post it threw that bug.

I checked, and it seems that the first posts are videos, with the first one being 991 MB, another 913 MB, and another 866 MB. The one that caused the error is 550 MB, which is this one: https://coomer.su/onlyfans/user/notsoamateurofficial/post/797304894. I also noticed that I had an issue with the previous post: https://coomer.su/onlyfans/user/notsoamateurofficial/post/821198748.

Despite trying to download multiple times, I concluded that the problem is not with the project or the user's internet, but rather something related to the server or the file itself, which might be corrupted or something similar. Since I recognize this as an issue, I will modify the system: now, instead of interrupting the download with an error message, the system will log the problematic files in a .txt file and skip to the next download. I will develop this solution and update it in the coming days. Thank you so much for the report; I had no idea this error existed.

**Comment by e43b** [comment]
@sergiohzph Damn, the error isn't occurring anymore. Hahaha, I don't know what happened yesterday; today it's downloading perfectly. Please test again, and if the error occurs again or if any other issue arises, open an issue—whether it's this one or a new one. You can also do it through Discord. Again, thank you for using the tool
